.github/workflows/artifactory.yml
.github/workflows/get_jfrog_access_token.sh
.github/workflows/get_jfrog_access_token_subject.sh

Refactor the pipeline to request artifactory token inplace.

Bug: Release pipeline must not reveal JFrog acces token

---

CHANGELOG.md

docs(changelog): Update CHANGELOG.md to from v0.11.0 to v1.0.0

---

CHANGELOG.md
src/intelligence_layer/core/model.py
tests/core/test_model.py

feat: add `context_size`-property to `AlephAlphaModel`

---

CHANGELOG.md
src/intelligence_layer/evaluation/evaluation/evaluator.py
tests/evaluation/test_diff_evaluator.py

feat: Add IncrementalEvaluator and IncrementalEvaluationLogic

---

CHANGELOG.md
pyproject.toml

docs: Update Changelog.md for new release

---

.readthedocs.yaml

fix: update read-the-docs poetry install

---

poetry.lock
pyproject.toml
tests/evaluation/test_instruct_comparison_argilla_evaluator.py

feat: remove pylama, faker, make deps more explicit

---

README.md

fix replace old repository name in link

---

CHANGELOG.md
pyproject.toml

- ...
- [na] Commit messages should contain a semantic [label](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and the ticket number

Bump minor version to 1.2.0

---

README.md

docs: Add elo how-to to readme

---

CHANGELOG.md
README.md
pyproject.toml

Bump major version to 2

---

CHANGELOG.md

This fix did not make it into the last release.
- ...

fix: Update document index entry in CHANGELOG.md

---

src/intelligence_layer/connectors/retrievers/qdrant_in_memory_retriever.py

chore: Replace deprecated `recreate_collection`-method.

---

.github/workflows/test-execution.yml

This should enable workflows for fork-pre
- ...

feat: change test execution to on-pull-request only

---

CHANGELOG.md
README.md

Changes in this PR are mainly contributions by [joshuakraftaa](https://github.com/joshuakraftaa).
The original PR however has been inactive for some weeks and it has become easier to copy the changes manually.
This will close PR #818
- ...

Update readme to close PR 818

---

.github/dependabot.yml

fix: remove unused dependabot configs

---

src/documentation/how_tos/how_to_human_evaluation_via_argilla.ipynb

fix: issue with the human eval how-to

---

CHANGELOG.md
src/intelligence_layer/evaluation/evaluation/evaluator/argilla_evaluator.py
src/intelligence_layer/evaluation/evaluation/evaluator/base_evaluator.py
src/intelligence_layer/evaluation/evaluation/evaluator/evaluator.py
src/intelligence_layer/evaluation/evaluation/evaluator/incremental_evaluator.py
tests/evaluation/test_evaluator.py

feat: Add `skip_example_on_any_failure` to `evaluate_runs`

---

CHANGELOG.md
src/documentation/evaluation.ipynb
tests/use_cases/classify/test_classify.py

fix: broken evaluation tutorial

---

CHANGELOG.md
src/intelligence_layer/core/__init__.py
src/intelligence_layer/core/model.py
tests/core/test_model.py

feat: harden model initialization

---

.github/workflows/sdk-tests.yml
docker-compose.yaml
tests/core/tracer/test_tracer.py

fix: reenable trace viewer integration test

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/intelligence_layer/core/detect_language.py
src/intelligence_layer/evaluation/evaluation/graders.py
tests/core/test_detect_language.py
tests/evaluation/evaluation/test_graders.py

feat: Replace langdetect with lingua

---

src/intelligence_layer/evaluation/dataset/domain.py

docs: docstring for `Example`

---

CHANGELOG.md
pyproject.toml

update changelog and pyproject

---

CHANGELOG.md
src/intelligence_layer/evaluation/evaluation/evaluator/base_evaluator.py
tests/evaluation/evaluation/test_evaluator.py

feat: add more tests about eval inconsistencies

---

.github/workflows/test-execution.yml

fix: re-enabled the ci pipeline on the main branch

---

CHANGELOG.md
pyproject.toml

Bump minor version to 4.1.0

---

src/intelligence_layer/core/__init__.py
tests/core/test_text_highlight.py

fix: make highlight test stable

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
poetry.lock
pyproject.toml

feat: better dependency management

---

tests/connectors/argilla/test_argilla_wrapper_client.py

fix: os-tests

---

src/intelligence_layer/evaluation/evaluation/domain.py
src/intelligence_layer/evaluation/run/domain.py

fix: defaults for metadata

---

docker-compose.yaml

add: postgres test database to docker compose

---

CHANGELOG.md
pyproject.toml

chore: bump version to v5.0.1

---

CHANGELOG.md
pyproject.toml

ci: bump versions to 5.0.2

---

CHANGELOG.md
pyproject.toml

- [ x] Review the code changes
- ...
- [ x] Update `changelog.md` if necessary
- [x ] Commit messages should contain a semantic [label](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and the ticket number

chore: bump patch version to v5.0.3

---

CHANGELOG.md
src/intelligence_layer/core/tracer/tracer.py
tests/connectors/document_index/test_document_index.py
tests/core/tracer/test_in_memory_tracer.py
tests/core/tracer/test_tracer.py

Fix error on taskspan

---

src/intelligence_layer/connectors/argilla/default_client.py
src/intelligence_layer/connectors/document_index/document_index.py
src/intelligence_layer/core/tracer/tracer.py
tests/core/tracer/test_in_memory_tracer.py
tests/examples/qa/test_single_chunk_qa.py

feat: Use urllib.urljoin where appropriate

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
docker-compose.yaml

fix: bump elastic version and adapt to new guide

---

src/intelligence_layer/core/model.py
tests/core/test_model.py

fix: prompt formatting and method docs in `ChatModel`

---

CHANGELOG.md
pyproject.toml

docs: Release 6.0

---

src/intelligence_layer/connectors/document_index/document_index.py

docs(document-index): update min_score and score description wrt. hybrid search

---

tests/connectors/document_index/test_document_index.py

test(document-index): use temporary collections

---

README.md
style_guide.md

refactor: update README with Contribution Guidelines

---

src/intelligence_layer/core/__init__.py
src/intelligence_layer/core/model.py
tests/core/test_model.py

feat: make ChatModels instruct capable

---

CHANGELOG.md

fix: add Changelog entry

---

CHANGELOG.md
pyproject.toml

feat: release 7.0.0

---

CHANGELOG.md
src/intelligence_layer/core/detect_language.py
tests/core/test_detect_language.py

make the task DetectLanguage support Polish and Catalan
- ...

make DetectLanguage support Polish and Catalan

---

CHANGELOG.md
src/documentation/elo_qa_eval.ipynb
src/intelligence_layer/connectors/limited_concurrency_client.py
tests/conftest.py
tests/connectors/test_limited_concurrency_client.py
tests/core/tracer/test_open_telemetry_tracer.py
tests/examples/qa/conftest.py
tests/examples/qa/test_single_chunk_qa.py

Improve test reliability

---

CHANGELOG.md
pyproject.toml

release: 7.1.0

---

CHANGELOG.md
pyproject.toml

feat: Release 7.2.0

---

CHANGELOG.md
src/intelligence_layer/examples/classify/prompt_based_classify.py
tests/examples/classify/test_prompt_based_classify.py

Make PromptBasedClassify support Llama3InstructModel
- ...

Make PromptBasedClassify support Llama3InstructModel

---

CHANGELOG.md
README.md
src/documentation/attention_manipulation_with_text_controls.ipynb

Add documentation about TextControl

---

.github/workflows/sdk-tests.yml
docker-compose.yaml
env.sample
tests/core/test_model.py

fix: local and ci test variables

---

src/intelligence_layer/connectors/studio/studio.py
src/intelligence_layer/evaluation/aggregation/aggregator.py
src/intelligence_layer/evaluation/benchmark/benchmark.py
src/intelligence_layer/evaluation/benchmark/studio_benchmark.py
tests/connectors/studio/conftest.py
tests/connectors/studio/test_studio.py
tests/connectors/studio/test_studio_benchmark.py
tests/evaluation/benchmark/test_benchmark.py
tests/evaluation/conftest.py
tests/evaluation/dataset/test_studio_data_repository.py
tests/evaluation/evaluation/test_evaluator_and_aggregator.py

feat: create benchmark class to run an evaluation

---

src/intelligence_layer/evaluation/benchmark/benchmark.py

fix: remove type in docstring

---

src/intelligence_layer/core/tracer/tracer.py

Doc: Add warning comment to PydanticSerializable

---

CHANGELOG.md
pyproject.toml

feat: Release 7.3.0

---

src/documentation/performance_tips.ipynb

docs: improve performance tips by making the example more explicit

---

CHANGELOG.md
pyproject.toml

release:8.0.0

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
docker-compose.yaml
env.sample
tests/learning/conftest.py

fix: update env of studio backend

---

CHANGELOG.md
pyproject.toml

docs: bump version to 9.0

---

CHANGELOG.md
pyproject.toml

Updates changelog and bumps patch version
- ...

docs: release v9.0.1

---

CHANGELOG.md
pyproject.toml

feat: Bump patch version

---

CHANGELOG.md
pyproject.toml

feat: Bump minor version

---

.pre-commit-config.yaml
src/documentation/attention_manipulation_with_text_controls.ipynb
src/documentation/classification.ipynb
src/documentation/document_index.ipynb
src/documentation/elo_qa_eval.ipynb
src/documentation/evaluate_with_studio.ipynb
src/documentation/evaluation.ipynb
src/documentation/fastapi_tutorial.ipynb
src/documentation/how_tos/how_to_aggregate_evaluations.ipynb
src/documentation/how_tos/how_to_create_a_dataset.ipynb
src/documentation/how_tos/how_to_define_a_task.ipynb
src/documentation/how_tos/how_to_evaluate_runs.ipynb
src/documentation/how_tos/how_to_human_evaluation_via_argilla.ipynb
src/documentation/how_tos/how_to_implement_a_simple_evaluation_and_aggregation_logic.ipynb
src/documentation/how_tos/how_to_implement_a_task.ipynb
src/documentation/how_tos/how_to_implement_elo_evaluations.ipynb
src/documentation/how_tos/how_to_implement_incremental_evaluation.ipynb
src/documentation/how_tos/how_to_log_and_debug_a_task.ipynb
src/documentation/how_tos/how_to_resume_a_run_after_a_crash.ipynb
src/documentation/how_tos/how_to_retrieve_data_for_analysis.ipynb
src/documentation/how_tos/how_to_run_a_task_on_a_dataset.ipynb
src/documentation/how_tos/studio/how_to_execute_a_benchmark.ipynb
src/documentation/how_tos/studio/how_to_upload_existing_datasets_to_studio.ipynb
src/documentation/how_tos/studio/how_to_use_studio_with_traces.ipynb
src/documentation/human_evaluation.ipynb
src/documentation/parameter_optimization.ipynb
src/documentation/performance_tips.ipynb
src/documentation/qa.ipynb
src/documentation/quickstart_task.ipynb
src/documentation/summarization.ipynb

Cleans up additional metadata when cleaning up notebooks. Running notebooks should no longer have lasting changes to the metadata
- ...

feat: Improve notebook cleanup on lint

---

CHANGELOG.md
pyproject.toml
src/documentation/elo_qa_eval.ipynb
src/documentation/how_tos/example_data.py
src/documentation/how_tos/studio/how_to_execute_a_benchmark.ipynb
src/intelligence_layer/connectors/studio/studio.py
src/intelligence_layer/evaluation/aggregation/domain.py
src/intelligence_layer/evaluation/dataset/domain.py
src/intelligence_layer/evaluation/dataset/in_memory_dataset_repository.py
src/intelligence_layer/evaluation/dataset/studio_dataset_repository.py
src/intelligence_layer/evaluation/run/runner.py
src/intelligence_layer/examples/qa/elo_qa_evaluation_logic.py
tests/connectors/argilla/test_argilla_wrapper_client.py
tests/connectors/studio/conftest.py
tests/connectors/studio/test_studio_benchmark.py
tests/connectors/studio/test_studio_dataset.py
tests/evaluation/aggregation/test_aggregation_repository.py
tests/evaluation/benchmark/test_benchmark.py
tests/evaluation/conftest.py
tests/evaluation/dataset/test_dataset_repository.py
tests/evaluation/dataset/test_studio_data_repository.py
tests/evaluation/evaluation/test_argilla_evaluator.py
tests/evaluation/evaluation/test_elo_evaluation_logic.py
tests/evaluation/evaluation/test_evaluation_repository.py
tests/evaluation/evaluation/test_evaluator_and_aggregator.py
tests/evaluation/run/test_run_repository.py
tests/evaluation/run/test_runner.py

fix(PHS-1093): studio & in memory dataset deserialization

---

.env.example
.github/workflows/artifactory.yml
.github/workflows/sdk-tests.yml
CHANGELOG.md
docker-compose.yaml
src/documentation/evaluation.ipynb
src/intelligence_layer/core/tracer/in_memory_tracer.py
src/intelligence_layer/core/tracer/tracer.py
src/intelligence_layer/examples/qa/elo_qa_evaluation_logic.py
tests/core/tracer/test_in_memory_tracer.py
tests/core/tracer/test_tracer.py

break: Remove deprecated Trace Viewer

---

tests/connectors/kernel/test_kernel.py
tests/connectors/studio/conftest.py

fix: connector tests

---

.github/workflows/artifactory.yml

fix: correct reference of composites scripts in artifactory.yml

---

scripts/test.sh

refactor: reduce number of workers for test script

---

CHANGELOG.md
pyproject.toml

chore: Bump version to v11.0.0

---

.env.example
.github/workflows/sdk-tests.yml
docker-compose.yaml
src/documentation/how_tos/example_data.py
src/intelligence_layer/connectors/studio/studio.py
tests/connectors/studio/test_studio.py

fix: remove local Studio service

---

CHANGELOG.md
src/intelligence_layer/connectors/studio/studio.py
tests/connectors/studio/test_studio.py

feat: raise error when multiple projects with same name exist

---

poetry.lock
pyproject.toml

chore: bump huggingface-hub>=0.33.5
