.github/workflows/sdk-tests.yml

Explicit installation of Sphinx is no longer necessary as it is already available. In addtion the wrong indenting of the corresponding lines in the `sdk-test.yml` caused the CI to fail if the CI does not use the chache.
- ...

fix: remove installation of sphinx in doctest workflow

---

CHANGELOG.md
src/intelligence_layer/examples/__init__.py
src/intelligence_layer/examples/classify/classify.py
tests/conftest.py
tests/evaluation/conftest.py
tests/use_cases/classify/test_classify.py

fix: Change `confusion_matrix` in `SingleLabelClassifyAggregationLogic` such that it can be persisted on disc
TASK: IL-475
- ...

fix: confusion matrix persistence on disc

---

src/documentation/document_index.ipynb

Updated Document Index Notebook to use MultipleChunkRetrieverQa instead of RetrieverBasedQa as it's deprecated.
- ...

Updated Document Index Notebook to use MultipleChunkRetrieverQa instead of RetrieverBasedQa

---

CHANGELOG.md
src/intelligence_layer/core/chunk.py
src/intelligence_layer/examples/search/expand_chunks.py
tests/use_cases/search/test_expand_chunk.py

fix: `ExpandChunks` is fast even for large documents

---

README.md

fix: Remove doubled occurence of elo how-to in readme

---

.github/dependabot.yml

Related dependabot issue: https://github.com/dependabot/dependabot-core/issues/9784
TASK: IL-525
- ...
- [NA] Update `changelog.md` if necessary

fix: Workaround for dependabot commit message bug

---

.github/dependabot.yml

Reverting workaround because bug has been fixed in dependabot.
This reverts commit 30c301e56fe5d93eaf21559773e417536e148e0a.
- ...
- [ NA] Update `changelog.md` if necessary
- [ NA] Commit messages should contain a semantic [label](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and the ticket number

Revert "fix: Workaround for dependabot commit message bug (#858)"

---

src/intelligence_layer/evaluation/infrastructure/file_system_based_repository.py

We run evaluations in parallel and for this a folder with results had to be created. This spuriously failed with `FileExistsError`.
Explanation for the bug:
- Assume two threads run `FileSystemBasedRepository.mkdir` to create the same directory 
- Thread1 and Thread2 both check that the directory does not exist
- Thread1 sucessfully creates the directory
- Thread2 tries to create the directory but fails with `FileExistsError` as the directory was already created by Thread1.
The result is that the entire evaluation fails with  `FileExistsError`.
- ...

fix: spurious mkdir failure if the file actually exists

---

CHANGELOG.md
Concepts.md
scripts/test.sh
src/intelligence_layer/connectors/argilla/argilla_client.py
src/intelligence_layer/evaluation/evaluation/evaluator/argilla_evaluator.py
tests/connectors/argilla/test_argilla_client.py
tests/evaluation/conftest.py
tests/evaluation/test_argilla_evaluator.py
tests/evaluation/test_instruct_comparison_argilla_evaluator.py

fix: naming in argilla evaluator

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
docker-compose.yaml
src/intelligence_layer/core/tracer/file_tracer.py
src/intelligence_layer/core/tracer/in_memory_tracer.py
src/intelligence_layer/core/tracer/tracer.py
tests/core/tracer/test_in_memory_tracer.py
tests/core/tracer/test_tracer.py

TASK: IL-496
- feat: `FileTracer` can convert files to new format
- All `Tracer`s have a `submit_to_trace_viewer()` method.
- ...

feat: Add function to upload to trace viewer to Tracer.

---

CHANGELOG.md
src/intelligence_layer/examples/search/expand_chunks.py
tests/examples/search/test_expand_chunk.py

Fixes an issue where indices were not properly passed when sub-chunking a text that started in the middle of a different text
- ...

fix: expand chunk index error for large texts

---

CHANGELOG.md
src/intelligence_layer/core/model.py
src/intelligence_layer/evaluation/aggregation/aggregator.py
src/intelligence_layer/evaluation/evaluation/evaluator/base_evaluator.py
tests/core/test_model.py
tests/evaluation/evaluation/test_evaluator.py

LRU cache on self methods are very much not recommended and can lead to significant memory consumptions. Therefore, we need to replace them
- ...

fix: lru_cache memory leak

---

CHANGELOG.md
src/intelligence_layer/core/prompt_template.py
src/intelligence_layer/examples/qa/single_chunk_qa.py
tests/core/test_prompt_template.py
tests/examples/qa/test_single_chunk_qa.py

fixes a bug where SingleChunkQa crashed on empty input if the input was not the first character in the prompt.
- ...

fix: SingleChunkQa crashing on specific prompt ordering

---

CHANGELOG.md
src/intelligence_layer/examples/qa/multiple_chunk_retriever_qa.py

fix: correct max highlight range

---

CHANGELOG.md
src/intelligence_layer/evaluation/evaluation/graders.py

…rrect float range of score
TASK: PHS-675
- ...

fix: Corrected docstrings for 'calculate_bleu'-function 

---

CHANGELOG.md
src/intelligence_layer/connectors/document_index/document_index.py
tests/connectors/document_index/test_document_index.py

- you can now specify a chunk overlap when configuring an index
- add validation to ensure 0 <= overlap < chunk_size
- add validation to ensure chunk_size is specified and valid
- ...

[DI-133] feat(document-index): integrate chunk overlap config

---

src/documentation/document_index.ipynb

- update Document Index jupyter notebook to include creation and assignment of index
- make default collection and index names less generic
- ...

[DI-133] docs(document-index): add indexes to notebook

---

CHANGELOG.md
src/documentation/qa.ipynb
src/intelligence_layer/examples/qa/multiple_chunk_qa.py
src/intelligence_layer/examples/qa/multiple_chunk_retriever_qa.py
src/intelligence_layer/examples/qa/retriever_based_qa.py
src/intelligence_layer/examples/qa/single_chunk_qa.py
tests/examples/qa/test_multiple_chunk_qa.py
tests/examples/qa/test_single_chunk_qa.py

vsp  - optional explainability in qa tasks per run

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
scripts/fastapi_example_test.sh
src/documentation/elo_qa_eval.ipynb
src/intelligence_layer/core/model.py
tests/core/test_model.py

fix: remove llama3.0 from models and defaults

---

CHANGELOG.md
src/documentation/document_index.ipynb
src/intelligence_layer/connectors/document_index/document_index.py
src/intelligence_layer/connectors/retrievers/document_index_retriever.py

This commit aligns optional parameters in the IL with the Document Index API.
- ...

[DI-206] feat: make Document Index search parameters optional

---

CHANGELOG.md
src/documentation/document_index.ipynb
src/intelligence_layer/connectors/document_index/document_index.py
tests/connectors/document_index/test_document_index.py

feat(document-index): add hybrid_index to index configuration

---

CHANGELOG.md
src/intelligence_layer/connectors/document_index/document_index.py
tests/connectors/document_index/test_document_index.py

fix(document-index): use chunk overlap when creating a new index

---

mypy.ini
scripts/lint.sh
src/intelligence_layer/evaluation/aggregation/accumulator.py
src/intelligence_layer/evaluation/aggregation/elo_aggregation.py
src/intelligence_layer/evaluation/evaluation/graders.py
src/intelligence_layer/learning/instruction_finetuning_data_handler.py
tests/connectors/test_limited_concurrency_client.py

This PR removes existing `# type: ignore` suppressions that are unnecessary. Having unused type ignores can be confusing when reading the code, and may actually lead to bugs, if they linger around and suppress a genuine bug in the future. To avoid issues caused by dead type ignores I've enabled the corresponding mypy check.
The PR also makes `lint.sh` agnostic to the current working directory (currently the linting results can differ depending on from which working directory it gets executed). 
- ...

chore: remove unused type ignores

---

src/intelligence_layer/connectors/document_index/document_index.py

Update DocumentInfo class to improve clarity and precision of its description and arguments, and refine the description of the list_documents method in DocumentIndexClient to better reflect its functionality.
- ...

docs: Update DocumentInfo and DocumentIndexClient

---

CHANGELOG.md
src/documentation/elo_qa_eval.ipynb
src/intelligence_layer/connectors/document_index/document_index.py
src/intelligence_layer/core/model.py

Update the `SearchQuery` model in `document_index.py` to allow a `min_score` between -1 and 1.
- ...

fix: allow negative min score in SearchQuery

---

CHANGELOG.md
src/intelligence_layer/connectors/document_index/document_index.py
tests/conftest_document_index.py
tests/connectors/document_index/test_document_index.py

Introduces a new metadata filter for the Document Index that allows to filter fields based on whether their value is null. 
- ...

feat(document-index): introduce `is_null` filter

---

src/intelligence_layer/connectors/studio/studio.py
src/intelligence_layer/evaluation/benchmark/studio_benchmark.py
src/intelligence_layer/evaluation/benchmark/trace_information.py
tests/evaluation/benchmark/test_benchmark.py
tests/evaluation/benchmark/test_trace_information.py

feat: show latency and token count in benchmark execution detail view

---

.github/workflows/sdk-tests.yml
CHANGELOG.md
src/intelligence_layer/connectors/kernel/kernel.py
tests/connectors/kernel/test_kernel.py

To allow for using Kernel Skills as either subtasks within an existing Task, or to pass into the Eval framework, this is a basic wrapper around a task that allows for invoking a skill as a Task.
The Pydantic types are passed into the constructor so that they can be callable and also to make mypy generics happy. You can check out the test to see how this would be used.
- ...

feat: new Pharia Kernel connector

---

CHANGELOG.md
docker-compose.yaml
src/intelligence_layer/connectors/studio/studio.py
tests/connectors/studio/test_studio_benchmark.py
tests/evaluation/benchmark/test_benchmark.py

fix: convert project_id to string

---

.github/workflows/document-index-tests.yml

fix: add CLIENT_URL to document-index-notebooks step in CI

---

src/intelligence_layer/evaluation/benchmark/studio_benchmark.py

I have added the option to set the number of parallel workers on the execution of a benchmark. This parameter will be passed directly to the runner.
Main reason for the change: some runs involve many API requests and the default (10) will result in timeouts or other concurrency issues. Consequently, valid runs fail due to the unavailability of the resources. Allowing for more control, one can avoid such situations by reducing the load on the API.

Add parameter max_workers to StudioBenchmark.execute
